### ISSUE TITLE
Metadata inherited to child spans

### ISSUE THREAD

**Issue by ludwikbukowski** [spandex-project/spandex_datadog#10]
When adding context to Trace and adding some custom metadata:
```
Spandex.Plug.AddContext.call(conn, tracer_opts: [tags: [custom_metadata: data]])
```

Looks that when it's sent to DatadogAgent, its replicating the `custom_metadata` per each span.
It produce a lot of binary data. What if I'd like to have sent it once, per root span, without replicating it for each child span?

**Comment by zachdaniel** [comment]
I think this issue ought to be brought up on the parent project `spandex` at https://github.com/spandex-project/spandex

If my answer doesn't fully address your question, please open the issue there!

This isn't well documented, but you can set the `private` key instead of `tags` and that meta will not be inherited by child spans.
