### ISSUE TITLE
Design questions: opts vs config; hand-carved back-pressure vs GenStage

### ISSUE THREAD

**Issue by garthk** [spandex-project/spandex_datadog#15]
G'day! I'm writing a variant on this with another observability platform as a target, and wondering whether there's something I'm missing about two choices:

* Passing options to `start_link/1`; and

* Implementing parallelism and back-pressure by hand.

I'm new to Elixir and trying to write the most idiomatic code I can. After a few blog posts, conference talks, and briefings from more senior Elixir devs, I'm tempted by default to write my new `Spandex.Adapter` using:

* `Mix.Config` for the options; and

* `GenStage` for a receive-transform-send pipeline with a pool of consumers at the tail end to send with limited parallelism and apply back-pressure as required.

Those idioms probably come with trade-offs, though, which @zachdaniel might well have taken into account back in August. What don't I know that I need to know?

**Comment by zachdaniel** [comment]
You don't want to access most configuration directly from the config because then the user will not have any way to override them with environment variables on their target machines. You should generally assume that they will not be compiling again in the target environment. 

As for using GenStage and other more evolved tools I see no problem with it :) The datadog api sender evolved over a while and had backpressure added to it piecemeal. I might advise you to take a look at open census instead of spandex, as all signs point towards open census becoming the new authority on tracing an elixir application (and any work I do will most likely go towards it instead of Spandex). https://github.com/opencensus-beam

**Comment by garthk** [comment]
Righto. Cheers!
